[project]
name = "dotnet_nlp.rule_engine.bundle"
#version = "1.0.0"
readme = "README.md"
license = {file="LICENSE"}
dynamic = ["version"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
    [tool.setuptools.packages.find]
    where = ["src"]

    [tool.setuptools.package-data]
    "dotnet_nlp.rule_engine.bundle" = ["runtimeconfig.json"]